---
# tasks file for roles/nagios

- name: update packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Pre-req for nagios
  apt:
     name: "{{ item }}"
  with_items:
    - apache2
    - libapache2-mod-php5
    - php5
    - nagios-plugins

- name: install system dependancies to help install/compile nagios
  apt:
    name: "{{ item }}"
  with_items:
    - wget
    - unzip
    - zip
    - autoconf
    - gcc
    - libc6
    - make
    - apache2-utils
    - libgd-dev
    - systemd
    - python-pip

- name: Install passlib
  pip:
    name: passlib
    state: present

- name: Create nagios user and group and add to www-data group
  user:
    name: nagios
    group: www-data

- name: Download Nagios 
  command: wget https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.2.tar.gz -O /tmp/nagios-4.4.2.tar.gz

- name: Extract Nagios
  unarchive:
    src: /tmp/nagios-4.4.2.tar.gz
    dest: /var/www/html
    remote_src: True

- name: Configigure nagios with apache enabled
  command: ./configure --with-httpd-conf=/etc/apache2/sites-enabled
  args:
    chdir: /var/www/html/nagios-4.4.2/ 

- name: Build nagios files
  command: make all
  args:
    chdir: /var/www/html/nagios-4.4.2/

- name: Install Nagios binary files
  command: make install
  args:
    chdir: /var/www/html/nagios-4.4.2/

- name: Install init script
  command: make install-init
  args:
    chdir: /var/www/html/nagios-4.4.2/

- name: Install commandmode to configure permissions
  command: make install-commandmode
  args:
    chdir: /var/www/html/nagios-4.4.2/

- name: Install nagios sample config files
  command: make install-config
  args:
    chdir: /var/www/html/nagios-4.4.2/

- name: Install Nagios configuration file for Apacahe web server
  command: make install-webconf
  args:
    chdir: /var/www/html/nagios-4.4.2/

- name: Create nagiosadmin account and a password
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: nagiospass

- name: Enable CGI
  apache2_module:
    state: present
    name: cgi
  notify:
    - restart apache

- name: Download NRPE
  command: curl -L -O https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz
  args:
    chdir: /home/vagrant

- name: Extract nrpe
  unarchive:
    src: /home/vagrant/nrpe-3.2.1.tar.gz
    dest: /home/vagrant
    remote_src: True

- name: Configure the check_nrpe plugin
  command: ./configure --disable-ssl
  args:
    chdir: /home/vagrant/nrpe-3.2.1

- name: Build and install check_nrpe
  command: "{{ item }}"
  args:
    chdir: /home/vagrant/nrpe-3.2.1
  with_items:
    - make check_nrpe
    - make install-plugin

- name: Uncomment the server cfg_dir
  lineinfile:
    path: /usr/local/nagios/etc/nagios.cfg
    regexp: "#cfg_dir=/usr/local/nagios/etc/servers"
    line: "cfg_dir=/usr/local/nagios/etc/servers"
    state: present

- name: Create Directory to store server config
  file:
    path: /usr/local/nagios/etc/servers
    state: directory

- name: Update the contact info
  replace:
    path: /usr/local/nagios/etc/objects/contacts.cfg
    regexp: "nagios@localhost"
    replace: "stephenkanyi7@gmail.com"

- name: Adds the check_nrpe to nagios config
  blockinfile:
    path: /usr/local/nagios/etc/objects/commands.cfg
    block: |
      define command {
          command_name    check_nrpe
          command_line    $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
      }

- name: Copy check plugins
  copy:
    src: "{{ item }}"
    dest: /usr/local/nagios/libexec/
  with_fileglob:
    - /usr/lib/nagios/plugins/check_*

- name: Add nagios service config
  template:
    src: templates/nagios.service
    dest: /etc/systemd/system/nagios.service

- name: Enable Nagios service
  command: systemctl enable /etc/systemd/system/nagios.service

- name: Start Nagios Service
  command: systemctl start nagios

- name: example on adding how to monitor serive(apache) on a host
  template:
    src: templates/lampserver.cfg
    dest: /usr/local/nagios/etc/servers/lampserver.cfg

# Remember to install nagios-nrpe-server and nagios-plugins on the host you want to monitor with nagios and configure it by adding the address of nagios server to /etc/nagios/nrpe.cfg
